/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import module.LottoGame;
import module.InvalidGameTypeException;          
import module.InvalidGameParametersException;
import controller.LottoGameController;          
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;    
/**
 *
 * @author wojtek
 */
public class LottoGameFrame extends javax.swing.JFrame {

    /** Controller for handling user actions and coordinating Model-View interaction */
    private controller.LottoGameController controller;
    
    /**
     * Creates new form LottoGameFrame
     */
    public LottoGameFrame() {
        controller = new controller.LottoGameController(); // DODAJ TO
        initComponents();
        initializeTable();
        setupAccessibility();
        setupTabOrder();
        updateGameInfo();
        setTitle("Lotto Number Generator");
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instrictionLabel = new javax.swing.JLabel();
        gameComboBox = new javax.swing.JComboBox<>();
        gameInfoLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        generateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        instrictionLabel.setLabelFor(gameComboBox);
        instrictionLabel.setText("Select Game Type");

        gameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lotto", "MultiMulti", "MiniLotto" }));
        gameComboBox.setToolTipText("");
        gameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameComboBoxActionPerformed(evt);
            }
        });

        gameInfoLabel.setText("Draws 6 numbers from 1 to 49");

        resultLabel.setText("Generated numbers:");

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Draw #", "Game Type", "Numbers"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultsTable);

        generateButton.setMnemonic('g');
        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        clearButton.setMnemonic('c');
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(instrictionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(123, 123, 123)
                                    .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)
                                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(178, 178, 178)
                                    .addComponent(gameInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 105, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrictionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(gameInfoLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateButton)
                    .addComponent(clearButton))
                .addGap(12, 12, 12)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Initializes the results table with proper model
 */
private void initializeTable() {
    // Create table if doesn't exist
    if (resultsTable == null) {
        resultsTable = new javax.swing.JTable();
    }
    
    // Set up table model
    resultsTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {
            "Draw #", "Game Type", "Numbers"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    
    // Replace TextArea with Table in scroll pane
    jScrollPane1.setViewportView(resultsTable);
}
    /**
 * Update game information label based on selected game type
 */
private void updateGameInfo() {
    String selectedGame = (String) gameComboBox.getSelectedItem();
    String info;
    
    try {
        LottoGame game = controller.createGame(selectedGame);
        info = controller.getGameInfo(game);
    } catch (InvalidGameTypeException | InvalidGameParametersException e) {
        info = "Invalid game configuration";
    }
    
    gameInfoLabel.setText(info);
}

/**
 * Generate lottery numbers based on selected game type
/**
 * Generates lottery numbers for the selected game type.
 * Delegates game creation and generation to Controller.
 */
private void generateNumbers() {
    try {
        String selectedGame = (String) gameComboBox.getSelectedItem();
        
        if (!controller.isValidGameType(selectedGame)) {
            showErrorDialog("No Game Selected", "Please select a valid game type.");
            return;
        }
        
        LottoGame game = controller.createGame(selectedGame);
        controller.generateNumbers(game);
        addResultToTable(game);
        
    } catch (InvalidGameTypeException e) {
        showErrorDialog("Invalid Game Type", e.getMessage());
    } catch (InvalidGameParametersException e) {
        showErrorDialog("Invalid Parameters", e.getMessage());
    } catch (Exception e) {
        showErrorDialog("Unexpected Error", 
            "An unexpected error occurred: " + e.getMessage());
    }
}

/**
 * Configures accessibility features for all interactive components.
 * Sets up tooltips, accessible descriptions, and mnemonic keys
 * to ensure the application is usable with screen readers and keyboard navigation.
 */

private void setupAccessibility() {
    // ComboBox accessibility
    gameComboBox.setToolTipText("Choose the type of lottery game");
    gameComboBox.getAccessibleContext().setAccessibleDescription(
        "Combo box for selecting lottery game type: Lotto, MultiMulti, or MiniLotto");
    
    // Generate button accessibility
    generateButton.setMnemonic('G');
    generateButton.setToolTipText("Generate random lottery numbers (Alt+G)");
    generateButton.getAccessibleContext().setAccessibleDescription(
        "Button to generate lottery numbers for selected game");
    
    // Clear button accessibility
    clearButton.setMnemonic('C');
    clearButton.setToolTipText("Clear all generated results (Alt+C)");
    clearButton.getAccessibleContext().setAccessibleDescription(
        "Button to clear the results table");
    
    // Table accessibility
    resultsTable.setToolTipText("Table showing generated lottery numbers");
    resultsTable.getAccessibleContext().setAccessibleDescription(
        "Table displaying history of generated lottery numbers with draw number, game type, and numbers");
    
    // Frame accessibility
    this.getAccessibleContext().setAccessibleDescription(
        "Lotto Number Generator application window");
}



/**
 * Display generated numbers in the result area
 * 
 * @param game the LottoGame with generated numbers
 */
private void addResultToTable(LottoGame game) {
    DefaultTableModel model = (DefaultTableModel) resultsTable.getModel();
    int drawNumber = model.getRowCount() + 1;
    
    List<Integer> numbers = game.getGeneratedNumbers();
    StringBuilder numbersString = new StringBuilder();
    
    for (int i = 0; i < numbers.size(); i++) {
        numbersString.append(String.format("%2d", numbers.get(i))); // .get(i) zamiast [i]
        if (i < numbers.size() - 1) {
            numbersString.append(", ");
        }
    }
    
    model.addRow(new Object[]{drawNumber, game.getGameName(), numbersString.toString()});
    
    int lastRow = model.getRowCount() - 1;
    resultsTable.setRowSelectionInterval(lastRow, lastRow);
    resultsTable.scrollRectToVisible(resultsTable.getCellRect(lastRow, 0, true));
}


/**
 * Displays an error message dialog to the user.
 * Used for reporting exceptions and validation errors in graphical form.
 * 
 * @param title the title of the error dialog
 * @param message the detailed error message to display
 */
private void showErrorDialog(String title, String message) {
    JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
}
    
    private void gameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameComboBoxActionPerformed
        updateGameInfo();
    }//GEN-LAST:event_gameComboBoxActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        generateNumbers();
    }//GEN-LAST:event_generateButtonActionPerformed

    
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        if (resultsTable != null) {
        DefaultTableModel model = (DefaultTableModel) resultsTable.getModel();
        model.setRowCount(0);
    }
    }//GEN-LAST:event_clearButtonActionPerformed

    

/**
 * Establishes logical tab order for keyboard navigation.
 * Defines the sequence: game selector → generate button → clear button → results table.
 * Ensures smooth navigation using Tab and Shift+Tab keys.
 */
private void setupTabOrder() {
    java.util.Vector<java.awt.Component> order = new java.util.Vector<>();
    order.add(gameComboBox);
    order.add(generateButton);
    order.add(clearButton);
    order.add(resultsTable);
    
    setFocusTraversalPolicy(new javax.swing.LayoutFocusTraversalPolicy() {
        @Override
        public java.awt.Component getComponentAfter(java.awt.Container focusCycleRoot, java.awt.Component aComponent) {
            int idx = order.indexOf(aComponent);
            if (idx >= 0) {
                idx = (idx + 1) % order.size();
                return order.get(idx);
            }
            return super.getComponentAfter(focusCycleRoot, aComponent);
        }
        
        @Override
        public java.awt.Component getComponentBefore(java.awt.Container focusCycleRoot, java.awt.Component aComponent) {
            int idx = order.indexOf(aComponent);
            if (idx >= 0) {
                idx = (idx - 1 + order.size()) % order.size();
                return order.get(idx);
            }
            return super.getComponentBefore(focusCycleRoot, aComponent);
        }
        
        @Override
        public java.awt.Component getFirstComponent(java.awt.Container focusCycleRoot) {
            return order.get(0);
        }
        
        @Override
        public java.awt.Component getLastComponent(java.awt.Container focusCycleRoot) {
            return order.get(order.size() - 1);
        }
    });
}
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> gameComboBox;
    private javax.swing.JLabel gameInfoLabel;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel instrictionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTable resultsTable;
    // End of variables declaration//GEN-END:variables
}
